Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.getcwd()
src	= Glob('*.c') + Glob('usb_hid_device/*.c')
CPPPATH = [cwd, str(Dir('#')),os.path.join(cwd, 'usb_hid_device')]
print 22222222222222222222222222222222
print CPPPATH
group = DefineGroup('USB', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
